#!/bin/bash 
  
mkdir 0 
  
echo blockMesh meshing... 
blockMesh > log.blockMesh

#echo snappyHexMesh...
#snappyHexMesh -overwrite	>	snappyHexMesh.log
#echo topoSet...

#topoSet > log.topoSet
#echo subsetMesh....
#subsetMesh -overwrite c0 -patch floatingObject

echo Preparing 0 folder... 
rm -fr 0 
cp -r 0.orig 0 
  
echo Setting the fields... 
setFields > log.setFields
  
echo Decomposing case... 
decomposePar > log.decomposePar 



echo Running... 
mpirun -np 8 --hostfile machines --rankfile rankfile interFoam -parallel > log.interFoam


echo Simulation complete. 
  
echo Reconstruct case... 
reconstructPar > log.reconstructPar 
echo Reconstruct complete. 

rm -rf pro*


